<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" total="1" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="20418" started-at="2017-03-10T07:17:32Z" finished-at="2017-03-10T07:17:52Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="20418" started-at="2017-03-10T07:17:32Z" finished-at="2017-03-10T07:17:52Z">
      <class name="testCases.Actitme_InviteSeveralUser">
        <test-method status="FAIL" signature="InviteSeveralUser()[pri:0, instance:testCases.Actitme_InviteSeveralUser@553f17c]" name="InviteSeveralUser" duration-ms="20387" started-at="2017-03-10T12:47:32Z" finished-at="2017-03-10T12:47:52Z">
          <exception class="java.lang.RuntimeException">
            <message>
              <![CDATA[java.lang.InstantiationException: pages.Act_UsersPage]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.RuntimeException: java.lang.InstantiationException: pages.Act_UsersPage
	at org.openqa.selenium.support.PageFactory.instantiatePage(PageFactory.java:134)
	at org.openqa.selenium.support.PageFactory.initElements(PageFactory.java:64)
	at testCases.Actitme_InviteSeveralUser.InviteSeveralUser(Actitme_InviteSeveralUser.java:39)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1198)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1123)
	at org.testng.TestNG.run(TestNG.java:1031)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:236)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:81)
Caused by: java.lang.InstantiationException: pages.Act_UsersPage
	at java.lang.Class.newInstance(Class.java:427)
	at org.openqa.selenium.support.PageFactory.instantiatePage(PageFactory.java:131)
	... 26 more
Caused by: java.lang.NoSuchMethodException: pages.Act_UsersPage.<init>()
	at java.lang.Class.getConstructor0(Class.java:3082)
	at java.lang.Class.newInstance(Class.java:412)
	... 27 more
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.RuntimeException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- InviteSeveralUser -->
      </class> <!-- testCases.Actitme_InviteSeveralUser -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
